name: petugas
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"



dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  splashscreen: ^1.3.5
  google_fonts: ^2.3.1
  carousel_images: ^1.1.2
  intl: ^0.17.0
  percent_indicator: ^3.4.0
  google_maps_flutter: ^2.1.3
  dio: ^4.0.6
  http: ^0.13.4
  curved_navigation_bar: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^1.0.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/iconp.png"
  remove_alpha_ios: true


flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/icons/
